name: ZylixWatch
options:
  bundleIdPrefix: com.zylix
  deploymentTarget:
    watchOS: "10.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "4"
    DEVELOPMENT_TEAM: ""
    CODE_SIGN_STYLE: Automatic
    ONLY_ACTIVE_ARCH: YES
    ARCHS: arm64
    SDKROOT: watchos
    SUPPORTS_MACCATALYST: NO

targets:
  ZylixWatch:
    type: application
    platform: watchOS
    sources:
      - path: ZylixWatch/Sources
        type: group
    resources:
      - path: ZylixWatch/Resources
        type: group
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zylix.watch
        INFOPLIST_FILE: ZylixWatch/Resources/Info.plist
        SWIFT_OBJC_BRIDGING_HEADER: ZylixWatch/Sources/Zylix-Bridging-Header.h
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        LIBRARY_SEARCH_PATHS:
          - $(inherited)
          - $(PROJECT_DIR)/ZylixWatch/Libraries
        OTHER_LDFLAGS:
          - -lzylix
        ENABLE_USER_SCRIPT_SANDBOXING: NO
        WATCHOS_DEPLOYMENT_TARGET: "10.0"
        SKIP_INSTALL: NO
        INSTALL_PATH: $(LOCAL_APPS_DIR)
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: -Onone
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
        Release:
          SWIFT_OPTIMIZATION_LEVEL: -O
          DEBUG_INFORMATION_FORMAT: dwarf-with-dsym
    preBuildScripts:
      - name: Build Zylix Core
        script: |
          set -e
          cd "${PROJECT_DIR}/../../core"

          # Determine target
          if [ "${PLATFORM_NAME}" = "watchsimulator" ]; then
            ZIG_TARGET="watchos-sim"
            LIB_DIR="watchos-simulator"
          else
            ZIG_TARGET="watchos"
            LIB_DIR="watchos"
          fi

          # Build Zylix Core
          echo "Building Zylix Core for ${ZIG_TARGET}..."
          zig build ${ZIG_TARGET} -Doptimize=ReleaseFast

          # Copy library
          mkdir -p "${PROJECT_DIR}/ZylixWatch/Libraries"
          cp "zig-out/${LIB_DIR}/libzylix.a" "${PROJECT_DIR}/ZylixWatch/Libraries/"
          echo "Copied libzylix.a to Libraries/"
        basedOnDependencyAnalysis: false

schemes:
  ZylixWatch:
    build:
      targets:
        ZylixWatch: all
    run:
      config: Debug
    test:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
